// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  portfolioSidebar: [{type: 'autogenerated', dirName: 'portfolio'}],
  skillsAgentsSidebar: [{type: 'autogenerated', dirName: 'skills-agents'}],
};

export default sidebars;
