// Paused per Richard's request (2026) — Oracle Utilities Data Intelligence
// Admin Guide card removed from the grid until he asks to bring it back.
// Updated href on file for whenever it returns:
// https://docs.oracle.com/en/industries/utilities/data-intelligence/266/data-intelligence-admin-guide/About-Oracle-Utilities-Data-Intelligence.html

export const technicalWriting = [
  {
    meta: 'Overview Guide',
    title: 'Opower Digital Energy Management',
    blurb: 'The complete guide to the Digital Self Service - Energy Management experience, from bill comparisons to data trends to solar power usage.',
    href: 'https://docs.oracle.com/en/industries/utilities/digital-self-service/energy-management-overview/energy-use-view-residential.html#GUID-34357E57-D562-412F-9DBA-ED8D9EEA431A',
    readLabel: 'Read the documentation',
    thumb: '/img/samples/dss-solar-bidirectional.png',
  },
  {
    meta: 'Design Document',
    title: 'High-Level Game Design Document',
    blurb: 'A design spec for an original game concept, redacted for public sharing.',
    href: '/files/Rabil-High-Level-Game-Design-Document-Calydon-Redacted.pdf',
    readLabel: 'View PDF',
    thumb: '/img/samples/game-design-document.png',
    internal: true,
  },
  {
    meta: 'Instructional Design',
    title: 'How to Generate Great-Looking Output Using Adobe RoboHelp',
    blurb: 'A recorded tutorial on how to format production-quality output from a RoboHelp project.',
    href: 'https://www.youtube.com/watch?v=fbQ2ypdel0I',
    readLabel: 'Watch the video',
    thumb: '/img/samples/robohelp-video.png',
  },
  {
    meta: 'Overview Guide',
    title: 'Opower Business Customer Engagement Overview',
    blurb: 'Documentation about an energy management software-as-a-service product for business owners who want to save energy.',
    href: 'https://docs.oracle.com/en/industries/utilities/business-customer-engagement/business-customer-engagement-overview/power-view.html#GUID-2CA91056-B3C6-49EE-B20F-BC25AEF63EF1',
    readLabel: 'Read the documentation',
    thumb: '/img/samples/bce-power-view.png',
  },
  {
    meta: 'Specification',
    title: 'Data Transfer Specifications',
    blurb: 'Documentation on transferring energy use data securely from utilities to Oracle in the right structure and format.',
    href: 'https://docs.oracle.com/en/industries/utilities/opower-platform/data-transfer/rates-data-file-specifications.html#GUID-0973077D-0779-414D-97AD-F687C19345DB',
    readLabel: 'Read the documentation',
    thumb: '/img/samples/data-transfer-spec.png',
  },
  {
    meta: 'Technical Report',
    title: 'Evaluation of Software Tools for Interactive Storytelling',
    blurb: 'A comparative evaluation of authoring tools for branching, interactive video game writing.',
    href: '/files/Rabil-Technical-Report-Software-Interactive-Storytelling.pdf',
    readLabel: 'View PDF',
    thumb: '/img/samples/technical-report-workflow.png',
    internal: true,
  },
  {
    meta: 'User Guide',
    title: 'Opower Analytics Visualization User Guide',
    blurb: 'How subject areas, measures, and attributes come together to build visualizations and inform business decisions.',
    href: 'https://docs.oracle.com/en/industries/utilities/opower-analytics-visualization/opower-av-user-guide/get-started-opower-av.html#GUID-46E22F9F-E5D5-41C6-829C-06803B7B0350',
    readLabel: 'Read the documentation',
    thumb: '/img/samples/av-user-guide.png',
  },
  {
    meta: 'Writing Workshop',
    title: 'Best Practices for Writing Procedures',
    blurb: 'A genericized internal training deck on procedure-writing standards and structure.',
    href: '/files/Procedure-Writing-Workshop.pdf',
    readLabel: 'View deck',
    thumb: '/img/samples/procedure-writing-workshop.png',
    internal: true,
  },
  {
    meta: 'Admin Guide',
    title: 'Data Refresh Procedure',
    blurb: 'A step-by-step administrative procedure, showing structure and voice on a real data-refresh task.',
    href: '/files/Refresh-Data-Intelligence-Data-Sample.pdf',
    readLabel: 'View PDF',
    thumb: '/img/samples/admin-guide-sample.png',
    internal: true,
  },
];

export const iaKm = [
  {
    meta: 'Article · April 2020',
    title: 'Best Practices for Content Reuse',
    blurb: 'Guidelines for reusing content safely across a documentation set without losing context.',
    href: 'https://richardrabil.com/2020/04/20/some-suggestions-for-content-reuse/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/content-reuse.png',
  },
  {
    meta: 'Article · Intercom, May 2019 (archived)',
    title: 'Content Strategy in Action: Enabling Sales with Product Documentation',
    blurb: 'How documentation structure became a sales enablement asset.',
    href: 'https://richardrabil.com/2023/12/21/my-article-from-stc-intercom-content-strategy-in-action-how-documentation-can-enable-sales/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/stc-intercom-article.png',
  },
  {
    meta: 'Article · A List Apart, July 2018',
    title: 'Order Out of Chaos: Patterns of Organization for Writing on the Job',
    blurb: 'Reusable organizational patterns for technical writing under real deadline pressure.',
    href: 'https://alistapart.com/article/order-out-of-chaos-patterns-of-organization-for-writing-on-the-job',
    readLabel: 'Read the piece',
    thumb: '/img/samples/alistapart-article.png',
  },
  {
    meta: 'Article · Intercom, October 2017 (archived)',
    title: "Designing Wiki Templates for Today's Web",
    blurb: 'Practical guidance for designing wiki page templates that hold up as content scales.',
    href: 'https://richardrabil.com/2018/06/12/my-article-from-stc-intercom-designing-wiki-templates-for-todays-web/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/wiki-template.png',
  },
  {
    meta: 'Presentation · SlideShare, November 2014',
    title: 'Getting Organized: Practical Guidelines for Documentation Scalability',
    blurb: 'An InfoDevDC meetup presentation on organizing documentation to scale with a growing team.',
    href: 'https://www.slideshare.net/slideshow/getting-organized-practical-guidelines-for-documentation-scalability/41119405',
    readLabel: 'View slides',
    thumb: '/img/samples/getting-organized-slide2.png',
  },
];

export const aiKnowledge = [
  {
    meta: 'Article · August 2026',
    title: 'On Delegating Tech Writing to AI: What We Gain and What We Lose',
    blurb: 'What actually transfers well to AI-delegated technical writing, and where there are risks to address.',
    href: 'https://richardrabil.com/2026/08/08/on-delegating-tech-writing-to-ai-what-we-gain-and-what-we-lose/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/ai-delegating.png',
  },
  {
    meta: 'Article · February 2026',
    title: 'Technical Writing Is Dead. Long Live Technical Writing!',
    blurb: 'Why the role is changing rather than disappearing as AI reshapes documentation work.',
    href: 'https://richardrabil.com/2026/02/28/technical-writing-is-dead-long-live-technical-writing/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/tw-is-dead.png',
  },
  {
    meta: 'Article · September 2025',
    title: 'Experiments with Generative AI: Simple Use Cases for Technical Writing',
    blurb: 'Early hands-on experiments applying generative AI to real technical writing tasks.',
    href: 'https://richardrabil.com/2025/09/04/experiments-with-generative-ai-simple-use-cases-for-technical-writing-and-reflections-on-writer-responsibility/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/genai-experiments.png',
  },
];

export const careerCraft = [
  {
    meta: 'Podcast · Document360, August 2025',
    title: 'Why Aesthetics Matter in Technical Docs, with Richard Rabil (Oracle)',
    blurb: 'A conversation on how visual design and usability shape whether documentation actually gets read.',
    href: 'https://document360.com/blog/why-aesthetics-matter-in-technical-docs-with-richard-oracle/',
    readLabel: 'Listen to the episode',
    thumb: '/img/samples/podcast-document360.png',
  },
  {
    meta: 'Article · August 2024',
    title: 'The Best Books on Technical Writing: An In-Depth Analysis',
    blurb: 'A survey and analysis of the field’s most useful books on the craft of technical writing.',
    href: 'https://richardrabil.com/2024/08/18/the-best-books-on-technical-writing-an-in-depth-analysis/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/best-books.png',
  },
  {
    meta: 'Article · December 2023',
    title: "There's No Such Thing as an Optimal Technical Writer to Developer Ratio",
    blurb: 'Why staffing ratios are a poor proxy for whether a documentation team is actually working.',
    href: 'https://richardrabil.com/2023/12/04/theres-no-such-thing-as-an-optimal-technical-writer-to-developer-ratio/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/writer-ratio.png',
  },
  {
    meta: 'Article · May 2023',
    title: 'On Aesthetics, Usability, and Technical Writing',
    blurb: 'Further research into how aesthetics and usability intersect with technical writing.',
    href: 'https://richardrabil.com/2023/05/17/notes-on-further-research-into-aesthetics-and-usability-and-what-it-means-for-technical-writers/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/aesthetics-usability.png',
  },
  {
    meta: 'Article · August 2018',
    title: 'Do Technical Writers Dream of Arbortext Editor?',
    blurb: 'A detailed analysis of the strengths and weaknesses of one of the most widely-used DITA XML authoring tools in the industry.',
    href: 'https://richardrabil.com/2018/08/10/do-technical-writers-dream-of-arbortext-editor/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/arbortext-dream.png',
  },
  {
    meta: 'Article · TechWhirl, March 2018',
    title: 'How to Be an Amazing Tech Comm Job Applicant: Tips from a Tech Comm Hiring Manager',
    blurb: 'Hiring-manager advice for standing out as a technical writing job applicant.',
    href: 'https://techwhirl.com/how-to-be-amazing-tech-comm-job-applicant-tips-tech-comm-hiring-manager/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/glasses-envelope.png',
  },
  {
    meta: 'Article · TechWhirl, July 2017',
    title: 'Evaluating Writing Samples: Strategies for TechComm Hiring Managers',
    blurb: 'Practical strategies for evaluating writing samples when hiring technical writers.',
    href: 'https://techwhirl.com/evaluating-writing-samples-strategies-techcomm-hiring-managers/',
    readLabel: 'Read the piece',
    thumb: '/img/samples/peacock.png',
  },
];
